// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ_Hn5BM4j8gGyC0tDwGJvoDgqsAjt94o',
    appId: '1:464745737843:web:ee327510d8824371644406',
    messagingSenderId: '464745737843',
    projectId: 'camera-intelligance-autozoom',
    authDomain: 'camera-intelligance-autozoom.firebaseapp.com',
    storageBucket: 'camera-intelligance-autozoom.appspot.com',
    measurementId: 'G-NNYJ6GQM76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7-N2JfqtErDjv3qTnzhZhOwdztZsTjIs',
    appId: '1:464745737843:android:a198d032527e58f9644406',
    messagingSenderId: '464745737843',
    projectId: 'camera-intelligance-autozoom',
    storageBucket: 'camera-intelligance-autozoom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALjFWWyt55Gy_Y8HA4f3a1qQiNY18D8Lc',
    appId: '1:464745737843:ios:95a5fd6172eade50644406',
    messagingSenderId: '464745737843',
    projectId: 'camera-intelligance-autozoom',
    storageBucket: 'camera-intelligance-autozoom.appspot.com',
    iosClientId: '464745737843-k043c4gbk11j5j05skddlten2u2kj0fo.apps.googleusercontent.com',
    iosBundleId: 'com.archit.cameraIntelliganceAutozoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALjFWWyt55Gy_Y8HA4f3a1qQiNY18D8Lc',
    appId: '1:464745737843:ios:95a5fd6172eade50644406',
    messagingSenderId: '464745737843',
    projectId: 'camera-intelligance-autozoom',
    storageBucket: 'camera-intelligance-autozoom.appspot.com',
    iosClientId: '464745737843-k043c4gbk11j5j05skddlten2u2kj0fo.apps.googleusercontent.com',
    iosBundleId: 'com.archit.cameraIntelliganceAutozoom',
  );
}
